### ISSUE TITLE
Which paper does this scheme come from?

### ISSUE THREAD

**Issue by tangyangyu** [Bohdat/Group-Signature-CL-Scheme#1]
Which paper does this scheme come from?

**Comment by rourouprograming** [comment]
Signature Schemes and Anonymous Credentials from Bilinear Maps

**Comment by rourouprograming** [comment]
Camenisch and Lysyanskaya wrote

**Comment by GitHub-Desk** [comment]
> Camenisch and Lysyanskaya wrote
I looked at it carefully! It's not this paper. Thanks！

**Comment by GitHub-Desk** [comment]
> Which paper does this scheme come from?

Do you know which paper it is？

**Comment by GitHub-Desk** [comment]
> Signature Schemes and Anonymous Credentials from Bilinear Maps
I looked at it carefully! It's not this paper. Thanks！


> Signature Schemes and Anonymous Credentials from Bilinear Maps

I looked at it carefully! It's not this paper. Thanks！
